// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EVCenterService.Models;

public partial class Invoice
{
    public int InvoiceId { get; set; }

    public Guid? SubscriptionId { get; set; }

    public decimal? Amount { get; set; }

    public string Status { get; set; }

    public DateTime? IssueDate { get; set; }

    public DateTime? DueDate { get; set; }

    public virtual Subscription Subscription { get; set; }
}