// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EVCenterService.Models;

public partial class Notification
{
    public int NotificationId { get; set; }

    public Guid? ReceiverId { get; set; }

    public string Content { get; set; }

    public string Type { get; set; }

    public DateTime? TriggerDate { get; set; }

    public bool? IsRead { get; set; }

    public virtual Account Receiver { get; set; }
}