// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EVCenterService.Models;

public partial class OrderService
{
    public int OrderId { get; set; }

    public int? VehicleId { get; set; }

    public Guid? UserId { get; set; }

    public DateTime AppointmentDate { get; set; }

    public string Status { get; set; }

    public string ChecklistNote { get; set; }

    public decimal? TotalCost { get; set; }

    public virtual ICollection<Feedback> Feedbacks { get; set; } = new List<Feedback>();

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();

    public virtual ICollection<PartsUsed> PartsUseds { get; set; } = new List<PartsUsed>();

    public virtual Slot Slot { get; set; }

    public virtual Account User { get; set; }

    public virtual Vehicle Vehicle { get; set; }
}