// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EVCenterService.Models;

public partial class Part
{
    public int PartId { get; set; }

    public string Name { get; set; }

    public string Type { get; set; }

    public string Brand { get; set; }

    public decimal? UnitPrice { get; set; }

    public virtual ICollection<PartsUsed> PartsUseds { get; set; } = new List<PartsUsed>();

    public virtual ICollection<Storage> Storages { get; set; } = new List<Storage>();
}