// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EVCenterService.Models;

public partial class PartsUsed
{
    public int UsageId { get; set; }

    public int? OrderId { get; set; }

    public int? PartId { get; set; }

    public int Quantity { get; set; }

    public string Note { get; set; }

    public virtual OrderService Order { get; set; }

    public virtual Part Part { get; set; }
}