// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EVCenterService.Models;

public partial class ServiceCatalog
{
    public int ServiceId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public decimal? BasePrice { get; set; }

    public int? DurationMinutes { get; set; }

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();
}