// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace EVCenterService.Models;

public partial class Slot
{
    [Key]
    public int SlotId { get; set; }

    public int? CenterId { get; set; }

    public Guid? TechnicianId { get; set; }

    public int? OrderId { get; set; }

    [DataType(DataType.DateTime)]
    public DateTime? StartTime { get; set; }

    [DataType(DataType.DateTime)]
    public DateTime? EndTime { get; set; }

    public virtual MaintenanceCenter Center { get; set; }

    public virtual OrderService Order { get; set; }

    public virtual Account Technician { get; set; }
}