// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EVCenterService.Models;

public partial class Storage
{
    public int StorageId { get; set; }

    public int? CenterId { get; set; }

    public int? PartId { get; set; }

    public int Quantity { get; set; }

    public int? MinThreshold { get; set; }

    public virtual MaintenanceCenter Center { get; set; }

    public virtual Part Part { get; set; }
}