// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EVCenterService.Models;

public partial class Subscription
{
    public Guid SubscriptionId { get; set; }

    public Guid? UserId { get; set; }

    public Guid? PlanId { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime EndDate { get; set; }

    public bool? AutoRenew { get; set; }

    public string Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<Invoice> Invoices { get; set; } = new List<Invoice>();

    public virtual SubscriptionPlan Plan { get; set; }

    public virtual Account User { get; set; }
}