// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EVCenterService.Models;

public partial class Vehicle
{
    public int VehicleId { get; set; }

    public Guid? UserId { get; set; }

    public string Vin { get; set; }

    public string Model { get; set; }

    public decimal? BatteryCapacity { get; set; }

    public decimal? Mileage { get; set; }

    public DateOnly? LastMaintenanceDate { get; set; }

    public virtual ICollection<OrderService> OrderServices { get; set; } = new List<OrderService>();

    public virtual Account User { get; set; }
}