// <auto-generated />
using System;
using EVCenterService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EVCenterService.Migrations
{
    [DbContext(typeof(EVServiceCenterContext))]
    [Migration("20251125085510_entitiesToVehicles")]
    partial class entitiesToVehicles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EVCenterService.Models.Account", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Certification")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FullName")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("UserId")
                        .HasName("PK__Account__1788CCAC376F95F8");

                    b.HasIndex(new[] { "Phone" }, "UQ__Account__5C7E359E226AF5C9")
                        .IsUnique()
                        .HasFilter("[Phone] IS NOT NULL");

                    b.HasIndex(new[] { "Email" }, "UQ__Account__A9D105341D624674")
                        .IsUnique();

                    b.ToTable("Account");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("a1a1a1a1-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Email = "admin@gmail.com",
                            FullName = "Admin",
                            Password = "AQAAAAIAAYagAAAAEKY2dgF4VNPd4Qd8a2SDsFH3bivFwAGSgBAkpTsdyEmWeZNZxzdM/kRKvsP74fSSiA==",
                            Phone = "0901000001",
                            Role = "Admin",
                            Status = "Active"
                        },
                        new
                        {
                            UserId = new Guid("b2b2b2b2-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Certification = "Battery System Certified;Brake System Certified",
                            Email = "tech1@gmail.com",
                            FullName = "Tran Van B",
                            Password = "AQAAAAIAAYagAAAAEGgARbnEgK18cvGa5lrcfc6furObiDwXNVp9c3E0ZLf7Rn1Hjb5io5/RAyaXSQQnEw==",
                            Phone = "0902000002",
                            Role = "Technician",
                            Status = "Active"
                        },
                        new
                        {
                            UserId = new Guid("c3c3c3c3-cccc-cccc-cccc-cccccccccccc"),
                            Certification = "Brake System Certified;Thermal & Cooling System Certified",
                            Email = "tech2@gmail.com",
                            FullName = "Le Thi C",
                            Password = "AQAAAAIAAYagAAAAEGZz42eKVHAeWVeXjAmd1iO5ZexxgrYDWNmDI2bae79kAzAA/gijsW+Em+Yf3gu8iA==",
                            Phone = "0903000003",
                            Role = "Technician",
                            Status = "Active"
                        },
                        new
                        {
                            UserId = new Guid("d4d4d4d4-dddd-dddd-dddd-dddddddddddd"),
                            Email = "staff@gmail.com",
                            FullName = "Phan Anh C",
                            Password = "AQAAAAIAAYagAAAAEOwBwJy6oCr174135i8X67kl3Hq8MwcsvsNR0qmRdMRy91wBQ6GUnRlVstNByaruag==",
                            Phone = "0906000006",
                            Role = "Staff",
                            Status = "Active"
                        },
                        new
                        {
                            UserId = new Guid("e5e5e5e5-eeee-eeee-eeee-eeeeeeeeeeee"),
                            Email = "user1@gmail.com",
                            FullName = "Pham Van D",
                            Password = "AQAAAAIAAYagAAAAEKPdqU5sfT1RddHYQEKZqUoQjaJDTzChJg7zP8N8ulvGNxDRqSfBH1qxRf7MXxr2Wg==",
                            Phone = "0904000004",
                            Role = "Customer",
                            Status = "Active"
                        },
                        new
                        {
                            UserId = new Guid("f6f6f6f6-ffff-ffff-ffff-ffffffffffff"),
                            Email = "user2@gmail.com",
                            FullName = "Do Thi E",
                            Password = "AQAAAAIAAYagAAAAECxa6gQ1j5Ap2TEnPUYg61CO22yloMgOKFHfjQNYKXEipwPiLntLk1V0AKdFdOBh0Q==",
                            Phone = "0905000005",
                            Role = "Customer",
                            Status = "Active"
                        },
                        new
                        {
                            UserId = new Guid("a3a3a3a3-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Certification = "Battery System Certified;Thermal & Cooling System Certified",
                            Email = "tech3@gmail.com",
                            FullName = "Nguyen Van F",
                            Password = "AQAAAAIAAYagAAAAEB3rEFrLRUYpOz1iDvWfNP9y/d7kz9nSEwL/UFRRlhdWyh33icD/4Vjk//X0Lnm/DA==",
                            Phone = "0908000008",
                            Role = "Technician",
                            Status = "Active"
                        },
                        new
                        {
                            UserId = new Guid("c5c5c5c5-cccc-cccc-cccc-cccccccccccc"),
                            Certification = "General Inspection Certified",
                            Email = "tech4@gmail.com",
                            FullName = "Vu Dinh H",
                            Password = "AQAAAAIAAYagAAAAEHnqBk1gH74ZefwhR/I6LOQniw4P2aM0fOJUTlVlcY2w5cCra0BOBFb9K/ao7SuHvQ==",
                            Phone = "0910000010",
                            Role = "Technician",
                            Status = "Active"
                        },
                        new
                        {
                            UserId = new Guid("b4b4b4b4-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Email = "staff2@gmail.com",
                            FullName = "Hoang Thi G",
                            Password = "AQAAAAIAAYagAAAAEC/TMqEdwKlc9XeTCR+5QafD6pKa4NWSjegvCKpEEfF1Og0GxM7+/61zwNlceUooRw==",
                            Phone = "0909000009",
                            Role = "Staff",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("EVCenterService.Models.Feedback", b =>
                {
                    b.Property<int>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FeedbackID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedbackId"));

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("OrderID");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserID");

                    b.HasKey("FeedbackId")
                        .HasName("PK__Feedback__6A4BEDF608B7A8D8");

                    b.HasIndex("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("Feedback");

                    b.HasData(
                        new
                        {
                            FeedbackId = 1,
                            Comment = "Excellent service! Technician was professional.",
                            CreatedAt = new DateTime(2025, 11, 25, 15, 55, 9, 208, DateTimeKind.Local).AddTicks(8139),
                            OrderId = 1,
                            Rating = 5,
                            UserId = new Guid("e5e5e5e5-eeee-eeee-eeee-eeeeeeeeeeee")
                        });
                });

            modelBuilder.Entity("EVCenterService.Models.Invoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("InvoiceID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceId"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("IssueDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("OrderID");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid?>("SubscriptionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SubscriptionID");

                    b.HasKey("InvoiceId")
                        .HasName("PK__Invoice__D796AAD5F01DE521");

                    b.HasIndex("OrderId");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("Invoice");

                    b.HasData(
                        new
                        {
                            InvoiceId = 1,
                            Amount = 999000m,
                            DueDate = new DateTime(2025, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IssueDate = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Paid",
                            SubscriptionId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            InvoiceId = 2,
                            Amount = 2500000m,
                            DueDate = new DateTime(2025, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IssueDate = new DateTime(2025, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderId = 1,
                            Status = "Paid"
                        },
                        new
                        {
                            InvoiceId = 3,
                            Amount = 2500000m,
                            DueDate = new DateTime(2025, 9, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IssueDate = new DateTime(2025, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderId = 3,
                            Status = "Paid"
                        },
                        new
                        {
                            InvoiceId = 4,
                            Amount = 2500000m,
                            DueDate = new DateTime(2025, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IssueDate = new DateTime(2025, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderId = 4,
                            Status = "Paid"
                        },
                        new
                        {
                            InvoiceId = 5,
                            Amount = 1000000m,
                            DueDate = new DateTime(2025, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IssueDate = new DateTime(2025, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderId = 5,
                            Status = "Paid"
                        });
                });

            modelBuilder.Entity("EVCenterService.Models.MaintenanceCenter", b =>
                {
                    b.Property<int>("CenterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CenterID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CenterId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<TimeOnly?>("CloseTime")
                        .HasColumnType("time");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<TimeOnly?>("OpenTime")
                        .HasColumnType("time");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("CenterId")
                        .HasName("PK__Maintena__398FC7D7AF460D18");

                    b.ToTable("MaintenanceCenter");

                    b.HasData(
                        new
                        {
                            CenterId = 1,
                            Address = "12 Le Loi, Q1, HCM",
                            CloseTime = new TimeOnly(18, 0, 0),
                            Email = "center1@evcenter.vn",
                            Name = "EV Center - District 1",
                            OpenTime = new TimeOnly(8, 0, 0),
                            Phone = "0281111111"
                        });
                });

            modelBuilder.Entity("EVCenterService.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("NotificationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("ReceiverId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ReceiverID");

                    b.Property<DateTime?>("TriggerDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Type")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("NotificationId")
                        .HasName("PK__Notifica__20CF2E32499BFD16");

                    b.HasIndex("ReceiverId");

                    b.ToTable("Notification");

                    b.HasData(
                        new
                        {
                            NotificationId = 1,
                            Content = "Your vehicle maintenance is completed.",
                            IsRead = false,
                            ReceiverId = new Guid("e5e5e5e5-eeee-eeee-eeee-eeeeeeeeeeee"),
                            TriggerDate = new DateTime(2025, 11, 25, 15, 55, 9, 208, DateTimeKind.Local).AddTicks(8118),
                            Type = "StatusUpdate"
                        },
                        new
                        {
                            NotificationId = 2,
                            Content = "Your appointment is scheduled for tomorrow.",
                            IsRead = false,
                            ReceiverId = new Guid("f6f6f6f6-ffff-ffff-ffff-ffffffffffff"),
                            TriggerDate = new DateTime(2025, 11, 25, 15, 55, 9, 208, DateTimeKind.Local).AddTicks(8120),
                            Type = "MaintenanceReminder"
                        });
                });

            modelBuilder.Entity("EVCenterService.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OrderDetailID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderDetailId"));

                    b.Property<int?>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("OrderID");

                    b.Property<int?>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int?>("ServiceId")
                        .HasColumnType("int")
                        .HasColumnName("ServiceID");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("OrderDetailId")
                        .HasName("PK__OrderDet__D3B9D30C5D8A0C85");

                    b.HasIndex("OrderId");

                    b.HasIndex("ServiceId");

                    b.ToTable("OrderDetail");

                    b.HasData(
                        new
                        {
                            OrderDetailId = 1,
                            OrderId = 1,
                            Quantity = 1,
                            ServiceId = 2,
                            UnitPrice = 1500000m
                        },
                        new
                        {
                            OrderDetailId = 2,
                            OrderId = 1,
                            Quantity = 1,
                            ServiceId = 3,
                            UnitPrice = 1000000m
                        },
                        new
                        {
                            OrderDetailId = 3,
                            OrderId = 2,
                            Quantity = 1,
                            ServiceId = 4,
                            UnitPrice = 1000000m
                        },
                        new
                        {
                            OrderDetailId = 4,
                            OrderId = 3,
                            Quantity = 1,
                            ServiceId = 2,
                            UnitPrice = 1500000m
                        },
                        new
                        {
                            OrderDetailId = 5,
                            OrderId = 3,
                            Quantity = 1,
                            ServiceId = 3,
                            UnitPrice = 1000000m
                        },
                        new
                        {
                            OrderDetailId = 6,
                            OrderId = 4,
                            Quantity = 1,
                            ServiceId = 2,
                            UnitPrice = 1500000m
                        },
                        new
                        {
                            OrderDetailId = 7,
                            OrderId = 4,
                            Quantity = 1,
                            ServiceId = 3,
                            UnitPrice = 1000000m
                        },
                        new
                        {
                            OrderDetailId = 8,
                            OrderId = 5,
                            Quantity = 1,
                            ServiceId = 4,
                            UnitPrice = 1000000m
                        });
                });

            modelBuilder.Entity("EVCenterService.Models.OrderService", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OrderID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime");

                    b.Property<string>("ChecklistNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid?>("TechnicianId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TechnicianID");

                    b.Property<decimal?>("TotalCost")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserID");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("int")
                        .HasColumnName("VehicleID");

                    b.HasKey("OrderId")
                        .HasName("PK__OrderSer__C3905BAFC93F21DA");

                    b.HasIndex("TechnicianId");

                    b.HasIndex("UserId");

                    b.HasIndex("VehicleId");

                    b.ToTable("OrderService");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            AppointmentDate = new DateTime(2025, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ChecklistNote = "Replaced brake pads, coolant check",
                            Status = "TechnicianCompleted",
                            TechnicianId = new Guid("b2b2b2b2-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            TotalCost = 2500000m,
                            UserId = new Guid("e5e5e5e5-eeee-eeee-eeee-eeeeeeeeeeee"),
                            VehicleId = 1
                        },
                        new
                        {
                            OrderId = 2,
                            AppointmentDate = new DateTime(2025, 10, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ChecklistNote = "General checkup",
                            Status = "Pending",
                            TotalCost = 1000000m,
                            UserId = new Guid("f6f6f6f6-ffff-ffff-ffff-ffffffffffff"),
                            VehicleId = 2
                        },
                        new
                        {
                            OrderId = 3,
                            AppointmentDate = new DateTime(2025, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ChecklistNote = "Replaced brake pads",
                            Status = "TechnicianCompleted",
                            TechnicianId = new Guid("c3c3c3c3-cccc-cccc-cccc-cccccccccccc"),
                            TotalCost = 2500000m,
                            UserId = new Guid("e5e5e5e5-eeee-eeee-eeee-eeeeeeeeeeee"),
                            VehicleId = 1
                        },
                        new
                        {
                            OrderId = 4,
                            AppointmentDate = new DateTime(2025, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ChecklistNote = "Coolant check",
                            Status = "TechnicianCompleted",
                            TechnicianId = new Guid("a3a3a3a3-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            TotalCost = 2500000m,
                            UserId = new Guid("f6f6f6f6-ffff-ffff-ffff-ffffffffffff"),
                            VehicleId = 2
                        },
                        new
                        {
                            OrderId = 5,
                            AppointmentDate = new DateTime(2025, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ChecklistNote = "General checkup",
                            Status = "TechnicianCompleted",
                            TechnicianId = new Guid("b2b2b2b2-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            TotalCost = 1000000m,
                            UserId = new Guid("e5e5e5e5-eeee-eeee-eeee-eeeeeeeeeeee"),
                            VehicleId = 1
                        });
                });

            modelBuilder.Entity("EVCenterService.Models.Part", b =>
                {
                    b.Property<int>("PartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PartID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PartId"));

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Type")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("PartId")
                        .HasName("PK__Part__7C3F0D3032B58819");

                    b.ToTable("Part");

                    b.HasData(
                        new
                        {
                            PartId = 1,
                            Brand = "Tesla",
                            Name = "EV Battery Pack",
                            Type = "Battery",
                            UnitPrice = 15000000m
                        },
                        new
                        {
                            PartId = 2,
                            Brand = "VinFast",
                            Name = "Charging Port",
                            Type = "Electrical",
                            UnitPrice = 3000000m
                        },
                        new
                        {
                            PartId = 3,
                            Brand = "Brembo",
                            Name = "Brake Pad",
                            Type = "Mechanical",
                            UnitPrice = 1000000m
                        },
                        new
                        {
                            PartId = 4,
                            Brand = "Shell",
                            Name = "Coolant Fluid",
                            Type = "Chemical",
                            UnitPrice = 500000m
                        });
                });

            modelBuilder.Entity("EVCenterService.Models.PartsUsed", b =>
                {
                    b.Property<int>("UsageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UsageID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsageId"));

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("OrderID");

                    b.Property<int?>("PartId")
                        .HasColumnType("int")
                        .HasColumnName("PartID");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("UsageId")
                        .HasName("PK__PartsUse__29B197C0E363B8D3");

                    b.HasIndex("OrderId");

                    b.HasIndex("PartId");

                    b.ToTable("PartsUsed");

                    b.HasData(
                        new
                        {
                            UsageId = 1,
                            Note = "Brake pads replaced",
                            OrderId = 1,
                            PartId = 3,
                            Quantity = 4
                        },
                        new
                        {
                            UsageId = 2,
                            Note = "Coolant refilled",
                            OrderId = 1,
                            PartId = 4,
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("EVCenterService.Models.ServiceCatalog", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ServiceID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceId"));

                    b.Property<decimal?>("BasePrice")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("ServiceId")
                        .HasName("PK__ServiceC__C51BB0EAA34714D3");

                    b.ToTable("ServiceCatalog");

                    b.HasData(
                        new
                        {
                            ServiceId = 1,
                            BasePrice = 10000000m,
                            Description = "Replace entire battery pack",
                            DurationMinutes = 240,
                            Name = "Battery Replacement"
                        },
                        new
                        {
                            ServiceId = 2,
                            BasePrice = 750000m,
                            Description = "Inspect and replace brake pads if needed",
                            DurationMinutes = 60,
                            Name = "Brake Check"
                        },
                        new
                        {
                            ServiceId = 3,
                            BasePrice = 800000m,
                            Description = "Check coolant and thermal management",
                            DurationMinutes = 45,
                            Name = "Cooling System Check"
                        },
                        new
                        {
                            ServiceId = 4,
                            BasePrice = 1000000m,
                            Description = "Full vehicle health check",
                            DurationMinutes = 180,
                            Name = "General Inspection"
                        });
                });

            modelBuilder.Entity("EVCenterService.Models.Slot", b =>
                {
                    b.Property<int>("SlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SlotID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SlotId"));

                    b.Property<int?>("CenterId")
                        .HasColumnType("int")
                        .HasColumnName("CenterID");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("OrderID");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("TechnicianId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TechnicianID");

                    b.HasKey("SlotId")
                        .HasName("PK__Slot__0A124A4F392B4E0A");

                    b.HasIndex("CenterId");

                    b.HasIndex("TechnicianId");

                    b.HasIndex(new[] { "OrderId" }, "UQ__Slot__C3905BAEB2FB822B")
                        .IsUnique()
                        .HasFilter("[OrderID] IS NOT NULL");

                    b.ToTable("Slot");

                    b.HasData(
                        new
                        {
                            SlotId = 1,
                            CenterId = 1,
                            EndTime = new DateTime(2025, 10, 5, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderId = 1,
                            StartTime = new DateTime(2025, 10, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            TechnicianId = new Guid("b2b2b2b2-bbbb-bbbb-bbbb-bbbbbbbbbbbb")
                        },
                        new
                        {
                            SlotId = 2,
                            CenterId = 1,
                            EndTime = new DateTime(2025, 10, 9, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2025, 10, 9, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            TechnicianId = new Guid("c3c3c3c3-cccc-cccc-cccc-cccccccccccc")
                        });
                });

            modelBuilder.Entity("EVCenterService.Models.Storage", b =>
                {
                    b.Property<int>("StorageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StorageID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StorageId"));

                    b.Property<int?>("CenterId")
                        .HasColumnType("int")
                        .HasColumnName("CenterID");

                    b.Property<int?>("MinThreshold")
                        .HasColumnType("int");

                    b.Property<int?>("PartId")
                        .HasColumnType("int")
                        .HasColumnName("PartID");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("StorageId")
                        .HasName("PK__Storage__8A247E37D28F7A41");

                    b.HasIndex("PartId");

                    b.HasIndex(new[] { "CenterId", "PartId" }, "UQ__Storage__2E4C37056410AAE2")
                        .IsUnique()
                        .HasFilter("[CenterID] IS NOT NULL AND [PartID] IS NOT NULL");

                    b.ToTable("Storage");

                    b.HasData(
                        new
                        {
                            StorageId = 1,
                            CenterId = 1,
                            MinThreshold = 3,
                            PartId = 1,
                            Quantity = 10
                        },
                        new
                        {
                            StorageId = 2,
                            CenterId = 1,
                            MinThreshold = 2,
                            PartId = 2,
                            Quantity = 5
                        },
                        new
                        {
                            StorageId = 3,
                            CenterId = 1,
                            MinThreshold = 3,
                            PartId = 3,
                            Quantity = 8
                        },
                        new
                        {
                            StorageId = 4,
                            CenterId = 1,
                            MinThreshold = 5,
                            PartId = 4,
                            Quantity = 15
                        });
                });

            modelBuilder.Entity("EVCenterService.Models.Subscription", b =>
                {
                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SubscriptionID");

                    b.Property<bool?>("AutoRenew")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("PlanId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PlanID");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("active");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserID");

                    b.HasKey("SubscriptionId")
                        .HasName("PK__Subscrip__9A2B24BD05B92A78");

                    b.HasIndex("PlanId");

                    b.HasIndex("UserId");

                    b.ToTable("Subscription");

                    b.HasData(
                        new
                        {
                            SubscriptionId = new Guid("33333333-3333-3333-3333-333333333333"),
                            AutoRenew = true,
                            CreatedAt = new DateTime(2025, 11, 25, 15, 55, 9, 208, DateTimeKind.Local).AddTicks(8056),
                            EndDate = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlanId = new Guid("22222222-2222-2222-2222-222222222222"),
                            StartDate = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "active",
                            UserId = new Guid("e5e5e5e5-eeee-eeee-eeee-eeeeeeeeeeee")
                        });
                });

            modelBuilder.Entity("EVCenterService.Models.SubscriptionPlan", b =>
                {
                    b.Property<Guid>("PlanId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PlanID");

                    b.Property<string>("Benefits")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("DurationDays")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("PriceVnd")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("PriceVND");

                    b.HasKey("PlanId")
                        .HasName("PK__Subscrip__755C22D706673C48");

                    b.HasIndex(new[] { "Code" }, "UQ__Subscrip__A25C5AA731620A2C")
                        .IsUnique();

                    b.ToTable("SubscriptionPlan");

                    b.HasData(
                        new
                        {
                            PlanId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Benefits = "1 free inspection/month",
                            Code = "BASIC",
                            DurationDays = 30,
                            IsActive = true,
                            Name = "Basic Care",
                            PriceVnd = 499000m
                        },
                        new
                        {
                            PlanId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Benefits = "3 free inspections",
                            Code = "PREMIUM",
                            DurationDays = 90,
                            IsActive = true,
                            Name = "Premium Care",
                            PriceVnd = 999000m
                        });
                });

            modelBuilder.Entity("EVCenterService.Models.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("VehicleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleId"));

                    b.Property<decimal?>("BatteryCapacity")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateOnly?>("LastMaintenanceDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("Mileage")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserID");

                    b.Property<string>("Vin")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("VIN");

                    b.HasKey("VehicleId")
                        .HasName("PK__Vehicle__476B54B29147CA38");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "Vin" }, "UQ__Vehicle__C5DF234C30687499")
                        .IsUnique();

                    b.ToTable("Vehicle");

                    b.HasData(
                        new
                        {
                            VehicleId = 1,
                            BatteryCapacity = 82.0m,
                            LastMaintenanceDate = new DateOnly(2025, 8, 15),
                            Mileage = 15000m,
                            Model = "VinFast VF8",
                            UserId = new Guid("e5e5e5e5-eeee-eeee-eeee-eeeeeeeeeeee"),
                            Vin = "VN123456789ABCDEFG"
                        },
                        new
                        {
                            VehicleId = 2,
                            BatteryCapacity = 75.5m,
                            LastMaintenanceDate = new DateOnly(2025, 9, 20),
                            Mileage = 22000m,
                            Model = "Tesla Model Y",
                            UserId = new Guid("f6f6f6f6-ffff-ffff-ffff-ffffffffffff"),
                            Vin = "VN999999999ABCDEFG"
                        });
                });

            modelBuilder.Entity("EVCenterService.Models.Feedback", b =>
                {
                    b.HasOne("EVCenterService.Models.OrderService", "Order")
                        .WithMany("Feedbacks")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK__Feedback__OrderI__6FE99F9F");

                    b.HasOne("EVCenterService.Models.Account", "User")
                        .WithMany("Feedbacks")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Feedback__UserID__70DDC3D8");

                    b.Navigation("Order");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EVCenterService.Models.Invoice", b =>
                {
                    b.HasOne("EVCenterService.Models.OrderService", "Order")
                        .WithMany("Invoices")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK_Invoice_OrderService");

                    b.HasOne("EVCenterService.Models.Subscription", "Subscription")
                        .WithMany("Invoices")
                        .HasForeignKey("SubscriptionId");

                    b.Navigation("Order");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("EVCenterService.Models.Notification", b =>
                {
                    b.HasOne("EVCenterService.Models.Account", "Receiver")
                        .WithMany("Notifications")
                        .HasForeignKey("ReceiverId")
                        .HasConstraintName("FK__Notificat__Recei__6C190EBB");

                    b.Navigation("Receiver");
                });

            modelBuilder.Entity("EVCenterService.Models.OrderDetail", b =>
                {
                    b.HasOne("EVCenterService.Models.OrderService", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK__OrderDeta__Order__5070F446");

                    b.HasOne("EVCenterService.Models.ServiceCatalog", "Service")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ServiceId")
                        .HasConstraintName("FK__OrderDeta__Servi__5165187F");

                    b.Navigation("Order");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("EVCenterService.Models.OrderService", b =>
                {
                    b.HasOne("EVCenterService.Models.Account", "Technician")
                        .WithMany("AssignedOrders")
                        .HasForeignKey("TechnicianId")
                        .HasConstraintName("FK_OrderService_Technician");

                    b.HasOne("EVCenterService.Models.Account", "User")
                        .WithMany("OrderServices")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__OrderServ__UserI__4CA06362");

                    b.HasOne("EVCenterService.Models.Vehicle", "Vehicle")
                        .WithMany("OrderServices")
                        .HasForeignKey("VehicleId")
                        .HasConstraintName("FK__OrderServ__Vehic__4BAC3F29");

                    b.Navigation("Technician");

                    b.Navigation("User");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("EVCenterService.Models.PartsUsed", b =>
                {
                    b.HasOne("EVCenterService.Models.OrderService", "Order")
                        .WithMany("PartsUseds")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK__PartsUsed__Order__5441852A");

                    b.HasOne("EVCenterService.Models.Part", "Part")
                        .WithMany("PartsUseds")
                        .HasForeignKey("PartId")
                        .HasConstraintName("FK__PartsUsed__PartI__5535A963");

                    b.Navigation("Order");

                    b.Navigation("Part");
                });

            modelBuilder.Entity("EVCenterService.Models.Slot", b =>
                {
                    b.HasOne("EVCenterService.Models.MaintenanceCenter", "Center")
                        .WithMany("Slots")
                        .HasForeignKey("CenterId")
                        .HasConstraintName("FK__Slot__CenterID__59063A47");

                    b.HasOne("EVCenterService.Models.OrderService", "Order")
                        .WithOne("Slot")
                        .HasForeignKey("EVCenterService.Models.Slot", "OrderId")
                        .HasConstraintName("FK__Slot__OrderID__5AEE82B9");

                    b.HasOne("EVCenterService.Models.Account", "Technician")
                        .WithMany("Slots")
                        .HasForeignKey("TechnicianId")
                        .HasConstraintName("FK__Slot__Technician__59FA5E80");

                    b.Navigation("Center");

                    b.Navigation("Order");

                    b.Navigation("Technician");
                });

            modelBuilder.Entity("EVCenterService.Models.Storage", b =>
                {
                    b.HasOne("EVCenterService.Models.MaintenanceCenter", "Center")
                        .WithMany("Storages")
                        .HasForeignKey("CenterId")
                        .HasConstraintName("FK__Storage__CenterI__45F365D3");

                    b.HasOne("EVCenterService.Models.Part", "Part")
                        .WithMany("Storages")
                        .HasForeignKey("PartId")
                        .HasConstraintName("FK__Storage__PartID__46E78A0C");

                    b.Navigation("Center");

                    b.Navigation("Part");
                });

            modelBuilder.Entity("EVCenterService.Models.Subscription", b =>
                {
                    b.HasOne("EVCenterService.Models.SubscriptionPlan", "Plan")
                        .WithMany("Subscriptions")
                        .HasForeignKey("PlanId")
                        .HasConstraintName("FK__Subscript__PlanI__656C112C");

                    b.HasOne("EVCenterService.Models.Account", "User")
                        .WithMany("Subscriptions")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Subscript__UserI__6477ECF3");

                    b.Navigation("Plan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EVCenterService.Models.Vehicle", b =>
                {
                    b.HasOne("EVCenterService.Models.Account", "User")
                        .WithMany("Vehicles")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Vehicle__UserID__3D5E1FD2");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EVCenterService.Models.Account", b =>
                {
                    b.Navigation("AssignedOrders");

                    b.Navigation("Feedbacks");

                    b.Navigation("Notifications");

                    b.Navigation("OrderServices");

                    b.Navigation("Slots");

                    b.Navigation("Subscriptions");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("EVCenterService.Models.MaintenanceCenter", b =>
                {
                    b.Navigation("Slots");

                    b.Navigation("Storages");
                });

            modelBuilder.Entity("EVCenterService.Models.OrderService", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("Invoices");

                    b.Navigation("OrderDetails");

                    b.Navigation("PartsUseds");

                    b.Navigation("Slot");
                });

            modelBuilder.Entity("EVCenterService.Models.Part", b =>
                {
                    b.Navigation("PartsUseds");

                    b.Navigation("Storages");
                });

            modelBuilder.Entity("EVCenterService.Models.ServiceCatalog", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("EVCenterService.Models.Subscription", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("EVCenterService.Models.SubscriptionPlan", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("EVCenterService.Models.Vehicle", b =>
                {
                    b.Navigation("OrderServices");
                });
#pragma warning restore 612, 618
        }
    }
}
